<?php 
/* -------------------------------------------------------------
This file is part of FreeDESK

FreeDESK is (C) Copyright 2012 David Cutting

FreeDESK is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

FreeDESK is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with FreeDESK.  If not, see www.gnu.org/licenses

For more information see www.purplepixie.org/freedesk/
-------------------------------------------------------------- */

// NOTE: DO NOT EDIT THIS FILE DIRECTLY FOR CUSTOMISATIONS!
// RATHER USE A PLUGIN MODULE OR OTHER USER-SCRIPT TO ADD DD
// DATA!

/**
 * FreeDESK Main Core Data Dictionary Definitions - do not edit as will be overwritten on upgrade
**/
class FreeDESK_DD
{
/**
 * Static exec function will setup the core data dictionary
 * @param mixed $DESK Instance of FreeDESK
**/
static function Exec(&$DESK)
{
	// System Log (syslog)
	
	$syslog = new DD_Table();
	$syslog->name = "SysLog";
	$syslog->entity = "syslog";
	
	$event_id = new DD_Field();
	$event_id->name = "Event ID";
	$event_id->field = "event_id";
	$event_id->type = DD_FieldType::Int;
	$event_id->searchable = true;
	$event_id->keyfield = true;
	$event_id->display = true;
	$syslog->Add($event_id);
	
	$event = new DD_Field();
	$event->name="Event";
	$event->field="event";
	$event->type=DD_FieldType::Char;
	$event->size=254;
	$event->searchable = true;
	$event->display = true;
	$syslog->Add($event);
	
	$event_class = new DD_Field();
	$event_class->name="Event Class";
	$event_class->field="event_class";
	$event_class->type=DD_FieldType::Char;
	$event_class->size=128;
	$event_class->searchable = true;
	$event_class->display = true;
	$syslog->Add($event_class);
	
	$event_type = new DD_Field();
	$event_type->name="Event Type";
	$event_type->field="event_type";
	$event_type->type=DD_FieldType::Char;
	$event_type->size=128;
	$event_type->searchable = true;
	$event_type->display = true;
	$syslog->Add($event_type);
	
	$event_level = new DD_Field();
	$event_level->name="Event Level";
	$event_level->field="event_level";
	$event_level->type=DD_FieldType::Int;
	$event_level->searchable = true;
	$event_level->display = true;
	$syslog->Add($event_level);
	
	$DESK->DataDictionary->AddTable($syslog);
	
	// System Configuration (sysconfig)
	
	$sysconfig = new DD_Table();
	$sysconfig->name="SysConfig";
	$sysconfig->entity="sysconfig";
	
	$sc_option = new DD_Field();
	$sc_option->name="SC Option";
	$sc_option->field="sc_option";
	$sc_option->type=DD_FieldType::Char;
	$sc_option->size=254;
	$sc_option->searchable=true;
	$sc_option->display=true;
	$sysconfig->Add($sc_option);
	
	$sc_value = new DD_Field();
	$sc_value->name="SC Value";
	$sc_value->field="sc_value";
	$sc_value->type=DD_FieldType::Char;
	$sc_value->size=254;
	$sc_value->searchable=true;
	$sc_value->display=true;
	$sysconfig->Add($sc_value);
	
	$DESK->DataDictionary->AddTable($sysconfig);
	
}

}

?>
